spring:
  profiles:
    active: prod
---
spring:
  profiles: dev
  datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: infodba
      password: infodba
      url: jdbc:sqlserver://localhost:1433;databaseName=tc
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
---
spring:
  profiles: dev
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
